### ISSUE TITLE
No target for "my-app" on prometheus

### ISSUE THREAD

**Issue by MarcioJales** [ContainerSolutions/k8s-deployment-strategies#3]
Hi,

When I follow the tutorial for the canary deployment, Grafana does not pull any data from Prometheus and thus cannot draw the graph. I've changed the prometheus service to be a NodePort, so that I can access it UI. The `/targets` path only show `http://localhost:9090/metrics`, despite there is much more targets definitions on configuration. Is this normal? How is Prometheus able to get data from `my-app` if there isn't any target to it?

Best Regards.

**Comment by MarcioJales** [comment]
Hi,

I figured out the problem.

I've inspected the logs in Prometheus server container and found out there was an authorization error message. Then I realized that there weren't `ServiceAccount`, `ClusterRole` and proper `ClusterRoleBinding` defined for Prometheus.

Then I've applied (as instructed by Prometheus docs) to minikube:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
```

Then I used `kubectl edit` to replace values for `serviceAccountName` and `serviceAccount` fields from `default` to `prometheus` in the Prometheus server's deployment. After that, all the jobs on Prometheus configuration that involved Kubernetes service discovery have shown up.

I guess those RBAC stuff are supposed to be part of the chart. Nevertheless, it will be helpful to add something regarding this issue to the tutorial.
